### ISSUE TITLE
plugin crash

### ISSUE THREAD

**Issue by steffenw94** [Mixaill/galaxy-integration-gw2#17]
Hello,

i get always the message "plugin is crashed" or "no answer"

here is log file:
[plugin-gw2-637b1fd4-b1d0-4de8-9bf6-757e639807f3.log](https://github.com/Mixaill/galaxy-integration-gw2/files/4977925/plugin-gw2-637b1fd4-b1d0-4de8-9bf6-757e639807f3.log)

**Comment by derrickb** [comment]
Same here, Galaxy client 2.0.23

Unfortunately the plugin crashes so often that it's unusable. Not seeing any other integrations (Battle.net,  Origin, Steam) ever crash.

**Comment by BattleMage** [comment]
Ever since the rewrite (Version 0.5) i'ts crashing for me, too.

Here is the strack trace from the crash. Crash happens every time, plugin isn't working at all.
```
2020-12-08 14:03:00,064 - root - ERROR - Plugin exception
Traceback (most recent call last):
  File "X:\GalaxyClient\plugin_runner.py", line 35, in <module>
    module = importlib.import_module(filename)
  File "X:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "%localappdata%\GOG.com\Galaxy\plugins\installed\gw2\plugin.py", line 44, in <module>
    release=("galaxy-integration-gw2@%s" % manifest['version']))
  File "%localappdata%\GOG.com\Galaxy\plugins\installed\gw2\3rdparty_windows\sentry_sdk\hub.py", line 106, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "%localappdata%\GOG.com\Galaxy\plugins\installed\gw2\3rdparty_windows\sentry_sdk\client.py", line 86, in __init__
    self._init_impl()
  File "%localappdata%\GOG.com\Galaxy\plugins\installed\gw2\3rdparty_windows\sentry_sdk\client.py", line 132, in _init_impl
    "auto_enabling_integrations"
  File "%localappdata%\GOG.com\Galaxy\plugins\installed\gw2\3rdparty_windows\sentry_sdk\integrations\__init__.py", line 105, in setup_integrations
    with_auto_enabling_integrations
  File "%localappdata%\GOG.com\Galaxy\plugins\installed\gw2\3rdparty_windows\sentry_sdk\integrations\__init__.py", line 41, in iter_default_integrations
    yield getattr(import_module(module), cls)
  File "X:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "%localappdata%\Local\GOG.com\Galaxy\plugins\installed\gw2\3rdparty_windows\sentry_sdk\integrations\aiohttp.py", line 25, in <module>
    from aiohttp import __version__ as AIOHTTP_VERSION
  File "%localappdata%\GOG.com\Galaxy\plugins\installed\gw2\3rdparty_windows\aiohttp\__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "%localappdata%\GOG.com\Galaxy\plugins\installed\gw2\3rdparty_windows\aiohttp\client.py", line 33, in <module>
    from yarl import URL
  File "%localappdata%\GOG.com\Galaxy\plugins\installed\gw2\3rdparty_windows\yarl\__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "%localappdata%\GOG.com\Galaxy\plugins\installed\gw2\3rdparty_windows\yarl\_url.py", line 58, in <module>
    @rewrite_module
  File "%localappdata%\GOG.com\Galaxy\plugins\installed\gw2\3rdparty_windows\yarl\_url.py", line 131, in URL
    _QUOTER = _Quoter(requote=False)
  File "yarl\_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'
```

I replaced the absolute path to the plugin with _%localappdata%_ and the path to galaxy with the drive _X:_

**Comment by Mixaill** [comment]
Please try v0.5.1, huge amoun of stability fixes were made. https://github.com/Mixaill/galaxy-integration-gw2/releases/tag/v0.5.1

**Comment by derrickb** [comment]
@Mixaill do the integrations update automatically, or do we need to manually download new builds? Don't see anything in Galaxy about integration versions/updates

**Comment by Mixaill** [comment]
It took some time (from days to weeks) to get it updated automatically, so the easiest way to test new update is to install it manually.

**Comment by steffenw94** [comment]
On my side, side have crashes every time i start the game

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Mikhail Paulyshka<mailto:notifications@github.com>
Gesendet: Sonntag, 13. Dezember 2020 11:07
An: Mixaill/galaxy-integration-gw2<mailto:galaxy-integration-gw2@noreply.github.com>
Cc: steffenw94<mailto:steffenwilhelm94@outlook.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Mixaill/galaxy-integration-gw2] plugin crash (#17)


It took some time (from days to weeks) to get it updated automatically, so the easiest way to test new update is to install it manually.

**Comment by Mixaill** [comment]
@steffenw94 Can you attach here or send to `me@mixaill.tk` this log file?

Windows: C:\ProgramData\GOG.com\Galaxy\logs\plugin-gw2-637b1fd4-b1d0-4de8-9bf6-757e639807f3.log
macOS: /Users/Shared/GOG.com/Galaxy/Logs/plugin-gw2-637b1fd4-b1d0-4de8-9bf6-757e639807f3.log

**Comment by steffenw94** [comment]
Hi

I found 3 different log files.

I attach you in zip file

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Mikhail Paulyshka<mailto:notifications@github.com>
Gesendet: Freitag, 18. Dezember 2020 21:40
An: Mixaill/galaxy-integration-gw2<mailto:galaxy-integration-gw2@noreply.github.com>
Cc: steffenw94<mailto:steffenwilhelm94@outlook.de>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [Mixaill/galaxy-integration-gw2] plugin crash (#17)


@steffenw94<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsteffenw94&data=04%7C01%7C%7Cdac17f0c23a842e0024308d8a3952dd7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637439208391756610%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RmhtVwvpfyE%2FtT1ii7rZ7Bkwyhcn0dJnOKhhtycbuzQ%3D&reserved=0> Can you attach here or send to me@mixaill.tk this log file?

Windows: C:\ProgramData\GOG.com\Galaxy\logs\plugin-gw2-637b1fd4-b1d0-4de8-9bf6-757e639807f3.log
macOS: /Users/Shared/GOG.com/Galaxy/Logs/plugin-gw2-637b1fd4-b1d0-4de8-9bf6-757e639807f3.log

**Comment by steffenw94** [comment]
Hi @Mixaill 

sorry i saw in my lost post the attachments wasnt included because i sent thius directly via email answer,

I Attach you the logs here

When you need more informations about this problem just tell me.
[GW2 Plugin Logs.zip](https://github.com/Mixaill/galaxy-integration-gw2/files/5826368/GW2.Plugin.Logs.zip)
